-- MySQL Script generated by MySQL Workbench
-- Thu Aug  4 08:52:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema julia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema julia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `julia` DEFAULT CHARACTER SET utf8mb4 ;
USE `julia` ;

-- -----------------------------------------------------
-- Table `julia`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  julia.venda (
  idvenda INT NOT NULL,
  cliente_id INT NOT NULL,
  data_e DATE NOT NULL,
  frete FLOAT(6,2) NOT NULL,
  PRIMARY KEY (`idvenda`));


-- -----------------------------------------------------
-- Table `julia`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS julia.cidade (
  idcidade INT NOT NULL,
  nome VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcidade`));


-- -----------------------------------------------------
-- Table `julia`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS julia.cliente (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  CPF BIGINT(16) NOT NULL,
  RG BIGINT(13) NOT NULL,
  endereco VARCHAR(45) NOT NULL,
  CEP BIGINT(8) NOT NULL,
  telefone BIGINT(8) NOT NULL,
  email VARCHAR(45) NOT NULL,
  estado VARCHAR(45) NOT NULL,
  cidade INT NOT NULL,
  senha VARCHAR(10) NOT NULL,
  tipocadastro VARCHAR(1) NOT NULL,
  clientecol VARCHAR(45) NOT NULL,
  venda_idvenda INT NOT NULL,
  cidade_idcidade INT NOT NULL,
  PRIMARY KEY (`id`, `cidade_idcidade`),
  CONSTRAINT `fk_cliente_venda1`
    FOREIGN KEY (`venda_idvenda`)
    REFERENCES julia.venda (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_cidade1`
    FOREIGN KEY (`cidade_idcidade`)
    REFERENCES julia.cidade (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `julia`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS julia.produto (
  id_produto BIGINT NOT NULL,
  tamanho VARCHAR(1) NULL,
  valor DOUBLE(10,2) NOT NULL,
  produto VARCHAR(50) NOT NULL,
  quantidade INT NOT NULL,
  PRIMARY KEY (`id_produto`));


-- -----------------------------------------------------
-- Table `julia`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS julia.fornecedor (
  id_fornecedor INT NOT NULL,
  nome VARCHAR(45) NOT NULL,
  telefone VARCHAR(45) NOT NULL,
  contato VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_fornecedor`));


-- -----------------------------------------------------
-- Table `julia`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS julia.compra (
  idcompra INT NOT NULL,
  produto INT NOT NULL,
  valor DOUBLE(10,2) NOT NULL,
  PRIMARY KEY (`idcompra`));


-- -----------------------------------------------------
-- Table `julia`.`comp_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS julia.comp_produto (
  id INT NOT NULL,
  entrada VARCHAR(45) NOT NULL,
  valor DOUBLE(10,2) NOT NULL,
  compra_idcompra INT NOT NULL,
  fornecedor_id_fornecedor INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comp_produto_compra1`
    FOREIGN KEY (`compra_idcompra`)
    REFERENCES julia.compra (`idcompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comp_produto_fornecedor1`
    FOREIGN KEY (`fornecedor_id_fornecedor`)
    REFERENCES julia.fornecedor (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `julia`.`ven_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS julia.ven_produto (
  id INT NOT NULL,
  valor DOUBLE(10,2) NULL,
  quantidade VARCHAR(45) NOT NULL,
  produto_id_produto INT NOT NULL,
  venda_idvenda INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ven_produto_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES julia.produto (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ven_produto_venda1`
    FOREIGN KEY (`venda_idvenda`)
    REFERENCES julia.venda (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `julia`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS julia.estoque (
  idestoque INT NOT NULL,
  entrada VARCHAR(45) NOT NULL,
  saida VARCHAR(45) NOT NULL,
  compra_idcompra INT NOT NULL,
  produto_id_produto BIGINT NOT NULL,
  PRIMARY KEY (`idestoque`),
  CONSTRAINT `fk_estoque_compra1`
    FOREIGN KEY (`compra_idcompra`)
    REFERENCES julia.compra (`idcompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoque_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES julia.produto (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `julia`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS julia.categoria (
  idcategoria INT NULL,
  tipodecategoria VARCHAR(45) NOT NULL,
  produto_id_produto BIGINT NOT NULL,
  PRIMARY KEY (`idcategoria`),
  CONSTRAINT `fk_categoria_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES julia.produto (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
